### PR TITLE
Add/GitHub actions

### PR DESCRIPTION
**Pull request by theavege**
<b>Hello!</b>

Thanks for your project. I add github-actions. I hope it is useful.

<i>Thanks.</i>

### CODE REVIEW

**Comment by theavege** [comment]
@motaz Could you accept the PR?

**Comment by motaz** [comment]
> @motaz Could you accept the PR?

I have stopped in development using Free Pascal and Lazarus long time ago, but I'm still using TurboBird admin tool to manage Firebird databases.
I can grant you permission to commit in main branch of TurboBird

**Comment by theavege** [comment]
@motaz Have you considered joining the [LXQT](https://lxqt-project.org/about/) project?
I think that joining Lazarus programs to the LXQT project will be mutually beneficial.

**Comment by motaz** [comment]
I have been moved to Go Language years a Go, I'm writing web services, specially microservices, which Golang is the best on it, after migration from Java for web development and web services, and I have left Desktop development for about 10 years
I have written a book about Go called (Migration to Go Language):
https://code.sd/books.html
I'm working on Telecom field, Java was dominant on this field, but Go now is strongly entering this important enterprise field

**Pull request merged**
